-- 1. What are the details of all cars purchased in the year 2022?

SELECT s.car_id,
       c.make,
       c.type,
       c.style,
       c.cost_$
FROM sales s
JOIN cars c
ON s.car_id=c.car_id
WHERE YEAR(s.purchase_date) = 2022;

-- 2. What is the total number of cars sold by each salesperson?

SELECT sp.name,
       COUNT(s.sale_id) AS total_cars_sold
FROM sales s
JOIN salespersons sp
ON s.salesman_id = sp.salesman_id
GROUP BY sp.name;

-- 3. What is the total revenue generated by each salesperson?

SELECT sp.name,
       SUM(c.cost_$) AS total_revenue
FROM sales s
JOIN cars c
ON s.car_id=c.car_id
JOIN salespersons sp 
ON s.salesman_id = sp.salesman_id
GROUP BY sp.name
ORDER BY total_revenue;

-- 4. What are the details of the cars sold by each salesperson?

SELECT sp.name,
       s.car_id,
       c.make,
       c.type,
       c.style,
       c.cost_$
FROM sales s
JOIN cars c
ON s.car_id=c.car_id
JOIN salespersons sp
ON s.salesman_id = sp.salesman_id;

-- 5. What is the total revenue generated by each car type?

SELECT c.type,
       SUM(c.cost_$) AS revenue
FROM cars c
JOIN sales s
ON c.car_id = s.car_id
GROUP BY c.type
ORDER BY revenue;

-- 6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?

SELECT c.make,
       c.type,
       c.style,
       c.cost_$
FROM sales s
JOIN cars c
ON s.car_id=c.car_id
JOIN salespersons sp
ON s.salesman_id = sp.salesman_id 
WHERE YEAR(s.purchase_date) = 2021 AND sp.name = 'Emily Wong';

-- 7. What is the total revenue generated by the sales of hatchback cars?

SELECT SUM(c.cost_$) AS total_revenue
FROM cars c
JOIN sales s
ON c.car_id = s.car_id
WHERE c.style = 'hatchback';

-- 8. What is the total revenue generated by the sales of SUV cars in the year 2022?

SELECT SUM(c.cost_$) AS total_revenue
FROM cars c
JOIN sales s
ON c.car_id = s.car_id
WHERE c.style = 'SUV' AND year(s.purchase_date) = 2022;

-- 9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?

SELECT sp.name ,
       sp.city ,
       COUNT(s.sale_id) AS total_cars_sold
FROM salespersons sp
JOIN sales s
ON sp.salesman_id = s.salesman_id
WHERE year(s.purchase_date) = 2023 
GROUP BY name , city
ORDER BY total_cars_sold DESC
LIMIT 1 ;

-- 10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?

SELECT sp.name ,
       sp.city ,
       SUM(c.cost_$) AS total_revenue
FROM salespersons sp
JOIN sales s
ON sp.salesman_id = s.salesman_id
JOIN cars c
ON s.car_id = c.car_id
WHERE year(s.purchase_date) = 2022
GROUP BY name , city
ORDER BY total_revenue DESC
LIMIT 1;

